services:

    DeliverTo\System:
      arguments: ['@google.map', '@delivery_to.schedule', '@deliver_to.message_gateway']

    delivery_to.schedule:
      class: InMemorySchedule

    deliver_to.message_gateway:
      class: InMemoryMessageGateway

    google.map:
        class: InFileMap
        public: true