services:

    DeliverTo\System:
      arguments: ['@google.map', '@deliver_to.schedule']

    deliver_to.schedule:
      class: InFileSchedule
      public: true

    deliver_to.message_gateway:
      class: InMemoryMessageGateway

    google.map:
      class: InFileMap
      public: true
        